services:
  backend:
    container_name: rowcounter-backend
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app

  frontend:
    container_name: rowcounter-frontend
    build: ./frontend
    ports:
      - 8000:5173
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  rowcounter-network:
    driver: bridge

volumes:
  frontend_node_modules:
